server:
  port: 20180

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    prefer-ip-address: true

spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false

database:
  datasource:
    pub:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    log:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    batch:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/BATCH?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/BATCH?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    crawling:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000