server:
  port: 20180

eureka:
  client:
    service-url:
      defaultZone: http://kimd0.iptime.org:20210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

spring:
  config:
    activate:
      on-profile: dev

database:
  datasource:
    pub:
      master:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    log:
      master:
        url: jdbc:mysql://mysql-20490:3306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000